apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ncorm4fbe-python
  janus-idp.io/tekton: ncorm4fbe-python
  backstage.io/kubernetes-id: ncorm4fbe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ncorm4fbe-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
